"""Independent, measured test-anchor views and their calibration-only controls.

Photographic plots stay local. Every section probes clean inputs only, for both
Standard and PGD-trained models. PGD describes the latter model's training, not
an attack generated by these views; this is not a robustness evaluation.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from matplotlib.patches import Rectangle
from torch import nn
from torch.nn import functional as F

from src.feature_methods import (
    capture_activations,
    channel_saliency,
    grad_cam,
    occlusion_map,
    receptive_field_box,
)
from src.feature_section_types import FeatureContext, FeatureSection, SectionData
from src.io_utils import sha256_file
from src.progress import tqdm
from src.stage_walkthrough import create_stage_walkthrough
from src.training import checkpoint_path

LAYERS = ["network.relu", "network.layer2", "network.layer4"]
LEVELS = ["Low · stem ReLU", "Mid · layer2", "High · layer4"]
FIELDS = [7, 99, 435]
SPECIES = ["cat", "dog"]


def _arm_label(ctx: FeatureContext) -> str:
    return {"standard": "Standard", "adversarial": "PGD-trained"}[ctx.arm]


@contextmanager
def _evaluation(model: nn.Module) -> Iterator[None]:
    """Clean inference must preserve deliberately mixed model modes."""
    modes = [(module, module.training) for module in model.modules()]
    model.eval()
    try:
        yield
    finally:
        for module, training in modes:
            module.training = training


def _np(value: torch.Tensor) -> np.ndarray[Any, Any]:
    return value.detach().cpu().numpy().copy()


def _resize(
    value: torch.Tensor, size: tuple[int, int], *, mode: str = "bilinear"
) -> np.ndarray[Any, Any]:
    arguments: dict[str, Any] = {"size": size, "mode": mode}
    if mode != "nearest":
        arguments["align_corners"] = False
    return _np(F.interpolate(value[None, None].float(), **arguments)[0, 0])


def _panel(axis: Any, image: np.ndarray[Any, Any], title: str) -> None:
    axis.imshow(image)
    axis.set_title(title, fontsize=9)
    axis.axis("off")


def _overlay(
    axis: Any, image: np.ndarray[Any, Any], heat: np.ndarray[Any, Any], title: str
) -> None:
    from src.feature_visualization import normalize_map

    _panel(axis, image, title)
    axis.imshow(normalize_map(heat), cmap="inferno", alpha=0.48, vmin=0, vmax=1)


def _base(ctx: FeatureContext) -> SectionData:
    return SectionData(
        payload={"anchors": [], "input_policy": "clean_only", "arm_label": _arm_label(ctx)},
        arrays={"anchor_sample_ids": np.asarray([record.sample_id for record in ctx.anchors])},
    )


def _clean_anchor(
    ctx: FeatureContext, index: int, data: SectionData
) -> tuple[torch.Tensor, dict[str, Any]]:
    record = ctx.anchors[index]
    pixels = ctx.anchor_pixels(index)
    with _evaluation(ctx.model), torch.no_grad():
        logits = ctx.model(pixels)[0]
    if logits.shape != (2,) or not bool(torch.isfinite(logits).all()):
        raise ValueError("anchor probes require two finite species logits")
    row = {
        "sample_id": record.sample_id,
        "label": record.label,
        "prediction": int(logits.argmax()),
        "clean_margin": float(logits[record.label] - logits[1 - record.label]),
    }
    data.arrays[f"anchor_{index}_clean_pixels"] = _np(pixels[0])
    data.arrays[f"anchor_{index}_clean_logits"] = _np(logits)
    data.payload["anchors"].append(row)
    return pixels, row


def _stages(ctx: FeatureContext) -> SectionData:
    data = _base(ctx)
    data.payload["stage_walkthroughs"] = []
    channels = ctx.stage_channels()
    checkpoint_sha = sha256_file(checkpoint_path(ctx.config, ctx.arm))
    for index, record in enumerate(
        tqdm(ctx.anchors, desc=f"{_arm_label(ctx)} · clean stage views", disable=not ctx.progress)
    ):
        pixels, _row = _clean_anchor(ctx, index, data)
        figure, metadata = create_stage_walkthrough(
            ctx.model,
            pixels,
            Path(record.image_path),
            channels,
            sample_id=record.sample_id,
            arm=ctx.arm,
            identity=ctx.identity,
            config_sha256=ctx.config.sha256,
            checkpoint_sha256=checkpoint_sha,
            true_label=record.label,
        )
        metadata["calibration_sample_ids"] = [item.sample_id for item in ctx.references]
        data.payload["stage_walkthroughs"].append(metadata)
        ctx.register(
            figure,
            f"stage-walkthrough-{record.sample_id}",
            "Original photograph and actual input through stem, pooling, residual stages, "
            "pooled features and the species head. Calibration-fixed channels show activations, "
            "not reconstructed photographs or verified semantic concepts; softmax is uncalibrated.",
            "stage_walkthrough",
            metadata=metadata,
        )
    return data


def _activations(ctx: FeatureContext) -> SectionData:
    """Show clean channel responses and local input sensitivity, never attacks."""
    data = _base(ctx)
    chosen = ctx.selected_channels()
    for index, record in enumerate(
        tqdm(ctx.anchors, desc=f"{_arm_label(ctx)} · clean activations", disable=not ctx.progress)
    ):
        pixels, row = _clean_anchor(ctx, index, data)
        clean = capture_activations(ctx.model, pixels, LAYERS)
        row["channel_peaks"] = {}
        image = _np(pixels[0]).transpose(1, 2, 0)
        size = (int(pixels.shape[-2]), int(pixels.shape[-1]))
        figure, axes = plt.subplots(4, 4, figsize=(15, 13), squeeze=False)
        _panel(axes[0, 0], image, "Actual clean input · pixels [0,1]")
        for axis in axes[0, 1:]:
            axis.axis("off")
        axes[0, 1].text(
            0,
            0.9,
            f"Model: {_arm_label(ctx)}\nTrue: {SPECIES[record.label]}\n"
            f"Predicted: {SPECIES[row['prediction']]}\n"
            f"True-species margin: {row['clean_margin']:.3f}\n\n"
            "Clean input only. No attacks are run.\n"
            "PGD-trained describes training.",
            va="top",
            fontsize=10,
        )
        axes[0, 2].text(
            0,
            0.9,
            "Channels are fixed by balanced\nclean calibration responses.\n\n"
            "This anchor chooses only among\nthose calibration-selected channels.\n\n"
            "A response is not a reconstructed\nphotograph or verified body-part detector.",
            va="top",
            fontsize=10,
        )
        axes[0, 3].text(
            0,
            0.9,
            "Response map: where a channel fires.\nRF box: theoretical spatial extent.\n"
            "Input gradient: local sensitivity.\n\n"
            "Overlays are display-normalized.\nFour anchors are illustrations,\n"
            "not accuracy or robustness evidence.",
            va="top",
            fontsize=10,
        )
        for level, layer in enumerate(LAYERS):
            # The anchor only chooses among channels already locked on calibration.
            channels = chosen[layer]
            if not channels:
                raise ValueError("activation view requires calibration-selected channels")
            channel = max(channels, key=lambda value: float(clean[layer][0, value].max()))
            raw = clean[layer][0, channel]
            y, x = divmod(int(raw.argmax()), int(raw.shape[1]))
            x0, y0, x1, y1 = receptive_field_box(layer, y, x, size[0])
            sensitivity = _resize(channel_saliency(ctx.model, pixels, layer, channel), size)
            clean_map = _np(raw)
            limit = max(float(clean_map.max()), 1e-6)
            plot_row = level + 1
            _panel(
                axes[plot_row, 0],
                image,
                f"{LEVELS[level]} · channel {channel}\npeak unit theoretical RF={FIELDS[level]}px",
            )
            axes[plot_row, 0].add_patch(
                Rectangle(
                    (x0, y0),
                    x1 - x0,
                    y1 - y0,
                    fill=False,
                    edgecolor="#00ff88",
                    linewidth=2,
                )
            )
            artist = axes[plot_row, 1].imshow(clean_map, cmap="inferno", vmin=0, vmax=limit)
            axes[plot_row, 1].set_title(
                f"Clean spatial response · {list(clean_map.shape)}\n"
                f"raw activation units [0,{limit:.3g}]",
                fontsize=9,
            )
            axes[plot_row, 1].axis("off")
            figure.colorbar(artist, ax=axes[plot_row, 1], shrink=0.65)
            low, high = float(raw.min()), float(raw.max())
            tolerance = max(1e-12, max(abs(low), abs(high)) * 1e-6)
            # Normalize before upsampling: rounding on a constant response must
            # not be exaggerated into an apparent spatially localized feature.
            display_response = (raw - low) / (high - low) if high - low > tolerance else raw * 0
            response_overlay = _resize(display_response, size)
            _overlay(
                axes[plot_row, 2],
                image,
                response_overlay,
                "Channel response location\nupsampled, display-normalized overlay",
            )
            _overlay(
                axes[plot_row, 3],
                image,
                sensitivity,
                "Input-gradient sensitivity\nof this channel's clean peak",
            )
            row["channel_peaks"][layer] = {
                "channel": channel,
                "clean_peak": float(raw.max()),
                "peak_grid_yx": [y, x],
                "receptive_field_xyxy": [x0, y0, x1, y1],
                "native_shape": list(raw.shape),
                "display_scale_max": limit,
                "selection_split": "calibration",
                "anchor_selection_rule": "strongest response among calibration-fixed channels",
            }
            for suffix, values in (
                (f"clean_map_{level}", clean_map),
                (f"clean_response_overlay_{level}", response_overlay),
                (f"channel_saliency_{level}", sensitivity),
            ):
                data.arrays[f"anchor_{index}_{suffix}"] = values
        figure.suptitle(
            f"{_arm_label(ctx)} · {record.sample_id} · clean input · true {SPECIES[record.label]}\n"
            "Spatial responses, theoretical receptive fields and local gradients "
            "are distinct probes",
        )
        ctx.register(
            figure,
            f"walkthrough-{record.sample_id}",
            "Fixed clean input with calibration-selected low/mid/high responses, theoretical "
            "RF boxes, response-location overlays and input-gradient sensitivity. "
            "PGD-trained names the training arm, not an attacked input. These probes show "
            "responses and local sensitivity, not training origin or causal body-part detectors.",
            "activation_walkthrough",
            metadata={
                "sample_id": record.sample_id,
                "input_policy": "clean_only",
                "arm_label": _arm_label(ctx),
                "channel_peaks": row["channel_peaks"],
            },
        )
    return data


def _attribution(ctx: FeatureContext, section: FeatureSection) -> SectionData:
    data = _base(ctx)
    figure, axes = plt.subplots(
        len(ctx.anchors),
        2,
        figsize=(9, len(ctx.anchors) * 3.5),
        squeeze=False,
        constrained_layout=True,
    )
    values = ctx.config.section("feature_visualization")
    for index, record in enumerate(
        tqdm(ctx.anchors, desc=f"{_arm_label(ctx)} · clean {section}", disable=not ctx.progress)
    ):
        pixels, row = _clean_anchor(ctx, index, data)
        image = _np(pixels[0]).transpose(1, 2, 0)
        size = (int(pixels.shape[-2]), int(pixels.shape[-1]))
        _panel(
            axes[index, 0],
            image,
            f"{record.sample_id}\ntrue={SPECIES[record.label]} · "
            f"predicted={SPECIES[row['prediction']]}\nmargin={row['clean_margin']:.3f}",
        )
        if section == "gradcam":
            native = grad_cam(ctx.model, pixels, record.label)
            cam = _resize(native, size)
            data.arrays[f"anchor_{index}_gradcam"] = cam
            data.arrays[f"anchor_{index}_gradcam_native"] = _np(native)
            row["gradcam_native_shape"] = list(native.shape)
            _overlay(
                axes[index, 1],
                image,
                cam,
                f"True-{SPECIES[record.label]} Grad-CAM\n"
                f"coarse {native.shape[0]}×{native.shape[1]} attribution",
            )
        else:
            result = occlusion_map(
                ctx.model,
                pixels,
                record.label,
                patch_size=int(values["occlusion_patch_size"]),
                stride=int(values["occlusion_stride"]),
                batch_size=ctx.config.integer("training", "evaluation_batch_size"),
            )
            drops = _np(result["score_drop"])
            data.arrays[f"anchor_{index}_occlusion_drop"] = drops
            data.arrays[f"anchor_{index}_occlusion_positions"] = _np(result["positions"])
            row["occlusion_base_margin"] = result["base_margin"]
            _panel(
                axes[index, 1],
                image,
                "Individual occlusion target-margin decrease\nred supports · blue suppresses",
            )
            up = _resize(result["score_drop"], size, mode="nearest")
            maximum = max(float(np.abs(up).max()), 1e-6)
            artist = axes[index, 1].imshow(
                up, cmap="RdBu_r", alpha=0.65, vmin=-maximum, vmax=maximum
            )
            figure.colorbar(artist, ax=axes[index, 1], shrink=0.7)
    figure.suptitle(
        f"{_arm_label(ctx)} · "
        f"{'class attribution' if section == 'gradcam' else 'patch-removal effects'}\n"
        "Target is the true species, even on errors; this is a clean-input diagnostic",
    )
    ctx.register(
        figure,
        section,
        (
            "True-species Grad-CAM on every fixed anchor. Each overlay is independently "
            "display-normalized; coarse attribution does not identify learned semantic parts."
            if section == "gradcam"
            else "Signed margin changes from masking one equal-area patch at a time "
            "with image-mean "
            "RGB. Positive drops support the true-species margin; negative drops suppress it. "
            "Masking is an input intervention, not proof of the region's role during learning."
        ),
        section,
        metadata={
            "sample_id": "fixed-test-anchor-set",
            "sample_ids": [record.sample_id for record in ctx.anchors],
            "target_labels": [record.label for record in ctx.anchors],
            "target_rule": "true species, including misclassified anchors",
        },
    )
    return data


def _aligned_dependencies(ctx: FeatureContext) -> tuple[SectionData, SectionData]:
    cam, occlusion = ctx.dependency("gradcam"), ctx.dependency("occlusion")
    expected = np.asarray([record.sample_id for record in ctx.anchors])
    for item in (cam, occlusion):
        if "anchor_sample_ids" not in item.arrays or not np.array_equal(
            item.arrays["anchor_sample_ids"], expected
        ):
            raise ValueError("diagnostic dependency anchor IDs are not aligned")
        rows = item.payload.get("anchors", [])
        if len(rows) != len(ctx.anchors) or any(
            row.get("sample_id") != record.sample_id or row.get("label") != record.label
            for row, record in zip(rows, ctx.anchors, strict=True)
        ):
            raise ValueError("diagnostic dependency anchor metadata is not aligned")
    for index in range(len(ctx.anchors)):
        for suffix in ("clean_pixels", "clean_logits"):
            key = f"anchor_{index}_{suffix}"
            if (
                key not in cam.arrays
                or key not in occlusion.arrays
                or not np.array_equal(cam.arrays[key], occlusion.arrays[key])
            ):
                raise ValueError("diagnostic dependency clean input/logit mismatch")
    return cam, occlusion


def _calibration_diagnostics(ctx: FeatureContext, data: SectionData) -> None:
    chosen = ctx.selected_channels()
    probe, baseline = ctx.reference_probe(), ctx.reference_probe(initial=True)
    labels = np.asarray([record.label for record in ctx.references])
    if not all(bool((labels == label).any()) for label in (0, 1)):
        raise ValueError("calibration response diagnostics need both species")
    responses, axes = plt.subplots(1, 3, figsize=(16, 4.5), constrained_layout=True)
    changes, change_axes = plt.subplots(1, 3, figsize=(16, 4.5), constrained_layout=True)
    data.payload["layers"] = {}
    for level, layer in enumerate(LAYERS):
        channels = chosen[layer]
        means, old = _np(probe[layer]["means"]), _np(baseline[layer]["means"])
        if means.shape != old.shape or len(means) != len(labels):
            raise ValueError("initial and trained calibration responses are not aligned")
        class_means = [
            means[labels == target][:, channels].mean(axis=0).tolist() for target in (0, 1)
        ]
        initial_mean = old[:, channels].mean(axis=0)
        relative = (
            (means[:, channels].mean(axis=0) - initial_mean)
            / np.maximum(np.abs(initial_mean), 1e-6)
        ).tolist()
        size = ctx.config.integer("input", "size")
        spatial = [size // (2 if level == 0 else 8 if level == 1 else 32)] * 2
        data.payload["layers"][layer] = {
            "selected_channels": channels,
            "calibration_mean_by_species": class_means,
            "relative_change_from_initial": relative,
            "spatial_shape": spatial,
            "receptive_field_pixels": FIELDS[level],
            "calibration_sample_ids": [record.sample_id for record in ctx.references],
        }
        data.arrays[f"calibration_means_{level}"] = means
        data.arrays[f"initial_calibration_means_{level}"] = old
        for target, color in ((0, "#7c3aed"), (1, "#ea580c")):
            axes[level].bar(
                np.arange(len(channels)) + (target - 0.5) * 0.35,
                class_means[target],
                0.35,
                label=SPECIES[target],
                color=color,
            )
        axes[level].set(
            xticks=np.arange(len(channels)),
            xticklabels=channels,
            title=LEVELS[level],
            xlabel="channel ID",
            ylabel="mean activation · raw units",
        )
        axes[level].legend()
        change_axes[level].bar(np.arange(len(channels)), relative, color="#0f766e")
        change_axes[level].set(
            xticks=np.arange(len(channels)),
            xticklabels=channels,
            title=LEVELS[level],
            xlabel="channel ID",
            ylabel="relative mean-response change",
        )
        change_axes[level].axhline(0, color="black", linewidth=0.8)
    data.arrays["calibration_sample_ids"] = np.asarray(
        [record.sample_id for record in ctx.references]
    )
    responses.suptitle(
        f"{_arm_label(ctx)} · balanced clean calibration ({len(ctx.references)} images)"
    )
    changes.suptitle(f"{_arm_label(ctx)} · fine-tuned versus matched ImageNet-initial responses")
    ctx.register(
        responses,
        "species-response",
        "Mean selected-channel responses to balanced clean calibration cats and dogs. "
        "Channels were selected on this same calibration reference, so this is descriptive, "
        "not held-out evidence of semantic specialization.",
        "species_response",
        shareable=True,
    )
    ctx.register(
        changes,
        "initial-response-change",
        "Relative mean-response changes against the matched ImageNet initialization on "
        "identical calibration inputs. Near-zero initial means can enlarge ratios; "
        "this is not a learning-from-scratch comparison.",
        "initial_response_change",
        shareable=True,
    )


def _diagnostics(ctx: FeatureContext) -> SectionData:
    # Delayed import avoids a cycle when the engine dispatches this module.
    from src.feature_visualization import _randomized, localization_comparison, map_correlation

    cam_data, occlusion_data = _aligned_dependencies(ctx)
    data = _base(ctx)
    _calibration_diagnostics(ctx, data)
    values = ctx.config.section("feature_visualization")
    seed = int(values["seed"])
    figure, axes = plt.subplots(
        len(ctx.anchors),
        3,
        figsize=(13, len(ctx.anchors) * 3.5),
        squeeze=False,
        constrained_layout=True,
    )
    modes = [(module, module.training) for module in ctx.model.modules()]
    randomized: nn.Module | None = None
    # Never keep the trained and randomized parameter sets on MPS together.
    ctx.model.cpu()
    try:
        randomized = _randomized(ctx.model, seed).to(ctx.device)
        for index, record in enumerate(
            tqdm(
                ctx.anchors,
                desc=f"{_arm_label(ctx)} · clean randomization controls",
                disable=not ctx.progress,
            )
        ):
            prefix = f"anchor_{index}_"
            pixels = ctx.anchor_pixels(index)
            if not np.array_equal(_np(pixels[0]), cam_data.arrays[prefix + "clean_pixels"]):
                raise ValueError("randomization-control input differs from cached attribution")
            original_cam = cam_data.arrays[prefix + "gradcam"]
            random_cam = _resize(
                grad_cam(randomized, pixels, record.label),
                (int(pixels.shape[-2]), int(pixels.shape[-1])),
            )
            controls = localization_comparison(
                original_cam,
                occlusion_data.arrays[prefix + "occlusion_positions"],
                occlusion_data.arrays[prefix + "occlusion_drop"],
                int(values["top_occlusion_tiles"]),
                int(values["random_occlusion_repeats"]),
                seed + index,
            )
            row = dict(cam_data.payload["anchors"][index])
            row.update(occlusion_data.payload["anchors"][index])
            row.update(controls)
            row["randomization_cam_correlation"] = map_correlation(original_cam, random_cam)
            data.payload["anchors"].append(row)
            for suffix in ("clean_pixels", "clean_logits", "gradcam"):
                data.arrays[prefix + suffix] = cam_data.arrays[prefix + suffix].copy()
            for suffix in ("occlusion_drop", "occlusion_positions"):
                data.arrays[prefix + suffix] = occlusion_data.arrays[prefix + suffix].copy()
            data.arrays[prefix + "randomized_gradcam"] = random_cam
            image = _np(pixels[0]).transpose(1, 2, 0)
            _panel(axes[index, 0], image, f"{record.sample_id}\ntrue {SPECIES[record.label]}")
            _overlay(axes[index, 1], image, original_cam, "Trained model · true-class Grad-CAM")
            _overlay(
                axes[index, 2],
                image,
                random_cam,
                "Fully randomized model · same target\nqualitative sanity control",
            )
    finally:
        if randomized is not None:
            randomized.cpu()
            del randomized
        if ctx.device.type == "mps":
            torch.mps.empty_cache()
        ctx.model.to(ctx.device)
        for module, training in modes:
            module.training = training
    figure.suptitle(
        f"{_arm_label(ctx)} · clean-input parameter-randomization control\n"
        "Overlays independently normalized; map similarity is descriptive"
    )
    ctx.register(
        figure,
        "randomization-control",
        "True-species Grad-CAM before and after full parameter randomization with a "
        "private CPU seed. Same inputs and targets; correlations can be undefined "
        "for flat maps and do not prove causal faithfulness.",
        "randomization_control",
        metadata={
            "sample_id": "fixed-test-anchor-set",
            "sample_ids": [record.sample_id for record in ctx.anchors],
            "target_labels": [record.label for record in ctx.anchors],
            "randomization_seed": seed,
        },
    )
    local, axis = plt.subplots(figsize=(11, 4.5), constrained_layout=True)
    rows = data.payload["anchors"]
    xaxis = np.arange(len(rows))
    count, repeats = int(values["top_occlusion_tiles"]), int(values["random_occlusion_repeats"])
    axis.bar(
        xaxis - 0.18,
        [row["top_gradcam_occlusion_mean_drop"] for row in rows],
        0.36,
        label=f"top {count} Grad-CAM tiles",
        color="#0f766e",
    )
    axis.bar(
        xaxis + 0.18,
        [row["random_occlusion_mean_drop"] for row in rows],
        0.36,
        label=f"mean of {repeats} random {count}-tile sets",
        color="#64748b",
    )
    axis.set(
        xticks=xaxis,
        xticklabels=[row["sample_id"] for row in rows],
        ylabel="mean individual true-class logit-margin decrease",
        title=f"{_arm_label(ctx)} · clean attribution-to-occlusion diagnostic",
    )
    axis.tick_params(axis="x", labelsize=8)
    axis.axhline(0, color="black", linewidth=0.8)
    axis.legend()
    ctx.register(
        local,
        "localization-summary",
        "Average single-tile occlusion effects in Grad-CAM-ranked versus random "
        "equal-area tiles. These are not jointly masked or additive effects; "
        "four anchors do not support a population claim.",
        "localization_summary",
        shareable=True,
    )
    return data


def compute_anchors(section: FeatureSection, ctx: FeatureContext) -> SectionData:
    """Compute exactly one requested family, leaving all other probes untouched."""
    existing_figures = set(plt.get_fignums())
    try:
        if section == "stages":
            return _stages(ctx)
        if section == "activations":
            return _activations(ctx)
        if section in {"gradcam", "occlusion"}:
            return _attribution(ctx, section)
        if section == "diagnostics":
            return _diagnostics(ctx)
        raise ValueError(f"unsupported anchor feature section: {section}")
    except BaseException:
        # Do not retain large unfinished photographic figures after a failed probe.
        for number in set(plt.get_fignums()) - existing_figures:
            plt.close(number)
        raise
